# Generated by Django 5.2 on 2025-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def seed_words_if_empty(apps, schema_editor):
    Word = apps.get_model('api', 'Word')
    if Word.objects.exists():
        return
    seed_list = [
        "apple", "brave", "crane", "delta", "eager", "flame",
        "grape", "hover", "ivory", "jolly", "karma", "lemon",
        "mango", "noble", "ocean", "pride", "quake", "raven",
        "solar", "tiger", "ultra", "vivid", "whale", "xenon",
        "young", "zebra",
    ]
    bulk = []
    for w in seed_list:
        bulk.append(Word(text=w, length=len(w), is_active=True))
    Word.objects.bulk_create(bulk, ignore_conflicts=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.')),
                ('text', models.CharField(db_index=True, help_text='Lowercase word text.', max_length=32, unique=True)),
                ('length', models.PositiveSmallIntegerField(db_index=True, help_text='Length of the word.')),
                ('is_active', models.BooleanField(default=True, help_text='If true, can be used as an answer in new games.')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['length', 'text'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.')),
                ('max_attempts', models.PositiveSmallIntegerField(default=6, help_text='Max number of guesses allowed.')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('target_word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_for_sessions', to='api.word')),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the record was last updated.')),
                ('guess_word', models.CharField(help_text='Lowercase guess text.', max_length=32)),
                ('result', models.CharField(blank=True, default='', help_text='Feedback pattern for the guess.', max_length=64)),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1-based attempt number within the session.')),
                ('is_correct', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='api.gamesession')),
            ],
            options={
                'verbose_name': 'Guess',
                'verbose_name_plural': 'Guesses',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='guess',
            unique_together={('session', 'attempt_number')},
        ),
        migrations.RunPython(seed_words_if_empty, reverse_code=migrations.RunPython.noop),
    ]
