# Generated by Django 5.2 on 2025-01-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, help_text='Difficulty level (1 = easiest).'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='hints_used',
            field=models.IntegerField(default=0, help_text='Number of hints used in this session.'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('timed', 'Timed'), ('daily', 'Daily'), ('endless', 'Endless')], default='classic', help_text='Gameplay mode identifier.', max_length=16),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_name',
            field=models.CharField(blank=True, help_text='Optional player display name.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='puzzle_type',
            field=models.CharField(default='word', help_text='Type of puzzle for this session (e.g., word, number).', max_length=32),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='time_limit_secs',
            field=models.PositiveIntegerField(blank=True, help_text='Optional time limit in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_time_secs',
            field=models.PositiveIntegerField(blank=True, help_text='Optional total time spent in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='guess',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Optional JSON metadata for the guess.', null=True),
        ),
    ]
